### ISSUE TITLE
Format for parsed KDL only indenting first child node

### ISSUE THREAD

**Issue by dj95** [kdl-org/kdl-rs#73]
Hi,

I try to write a CLI, that formats KDL documents. Therefore I want to use the `KdlDocument::fmt()` function to achieve this.

While writing the first little unit test, I found a weird behaviour within the format output. When the following document is formatted, only the first node is indented correctly.

**Input**

```javascript
world prop="value" {
child 1
child 2
}
```

**Output**

```javascript
world prop="value" {
    child 1
child 2
}
```

**Expected Output**

```javascript
world prop="value" {
    child 1
    child 2
}
```

Is the expected  behaviour intended? For testing the issue, here is the source code for reproduction. Please feel free to message me in case you need some more details.

```rust
use kdl::KdlDocument;

pub fn format_document(input: &str) -> miette::Result<String> {
    let mut doc: KdlDocument = input.parse()?;

    doc.fmt();

    Ok(doc.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_format_document() {
        let input = r#"
world prop="value" {
child 1
child 2
}
        "#;

        let exp = r#"world prop="value" {
    child 1
    child 2
}
"#;

        let res = format_document(input);

        assert!(res.is_ok());
        let res = res.unwrap();
        assert_eq!(res, exp);
    }
}
```

<img width="873" alt="Screenshot 2024-04-23 at 10 37 49" src="https://github.com/kdl-org/kdl-rs/assets/4348959/3a481b1c-a10d-4a3d-b5eb-bbe87235fc20">

**Comment by zkat** [comment]
oh huh. Thanks for the report. I'm rewriting the formatting stuff as part of the new kdlv2 parser rewrite, so I'll make sure this works this time around!

**Comment by dj95** [comment]
Thanks a lot!

When the `KdlDocument` is created manually within the Rust function, it seems to format properly. So I'm not sure whether it's a bug in the parser or the formatter. Or maybe in a mix of both.

**Comment by dj95** [comment]
Fixed in the new 6.0.0 release. I just updated to the newest version, replaced `fmt()` with `autofmt()` and all of the unit tests for my formatter passed.

Thanks a lot for working on this!

**Comment by zkat** [comment]
Hah. Amazing. I thought the formatter was still completely broken (it’s still failing some corner cases so I’ve had to disable the big auto format test for now)

Also, @dj95: I was considering writing my own small cli for this, but if you’re already doing formatting stuff, would you consider having an option to have your tool translate between v1 and v2 (and vice versa)? There’s methods exposed for this in 6.0.0. And you might want an option to retain as much formatting as possible (which is the default)

**Comment by dj95** [comment]
Sure. But the CLI is very much at the beginning as I stopped on it when I raised this issue. It's really awesome, that you've built these conversion functions into the crate. Will definitely give it a try!

**Comment by dj95** [comment]
Works like a charm! Build the v1 and v2 conversion (in both directions) into it. With some smaller KDL documents it works flawless.

Here's the code, if you'd like to take a look: https://github.com/dj95/kdl-fmt
